### ISSUE TITLE
How to remove the characters near year

### ISSUE THREAD

**Issue by ragulml03** [zhhlmr/ZHDatePicker#1]

**Comment by zhhlmr** [comment]
Hi there:

Not sure about which character you're indicating to. 

Do you mean the '年'?

**Comment by ragulml03** [comment]
yes

**Comment by zhhlmr** [comment]
You can edit this character in "pickerView: viewForRow: forComponent: reusingView:" in ZHDatePicker.m , which is https://github.com/zhhlmr/ZHDatePicker/blob/master/ZHDatePicker/ZHDatePicker.m#L327 . 

Probably , I'll add a custom variable or function about this later.

**Comment by ragulml03** [comment]
Thats great

Regards,
Ragul ML
